services:
  audibleismissing:
    container_name: audibleismissing
    image: ghcr.io/audibleismissing/audibleismissing:latest
    ports:
      - 8192:8000
    volumes:
      - ${CONFIG_PATH}:${CONFIG_DIR}
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - CONFIG_DIR=${CONFIG_DIR}