services:
  audibleismissing-dev:
    container_name: audibleismissing-dev
    build:
      context: ..
      dockerfile: Dockerfile-dev
    ports:
      - 8000:8000
    environment:
      - ALLOWED_ORIGINS="https://aim.example.com" # Set if running on something other than localhost or 127.0.0.1
    volumes:
      - ../config:/config
    develop:
      # Create a `watch` configuration to update the app
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ..
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ../pyproject.toml
