services:
  audibleismissing:
    container_name: audibleismissing
    image: ghcr.io/audibleismissing/audibleismissing:latest
    ports:
      - 8000:8000
    volumes:
      - ../config:/config
    environment:
      - ALLOWED_ORIGINS="https://aim.example.com"
      - CONFIG_DIR=/config